# Name your project
name: dbt_netflix
version: 1.0.0

# Profile to use
profile: dbt_netflix

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_netflix:
    intermediate:
      +materialized: table
    mart:
      +materialized: table
    staging:
      +materialized: view